### ISSUE TITLE
How do i test this?

### ISSUE THREAD

**Issue by Emekaborisama** [marquisvictor/Advanced-CSS#1]
Pls, how can i test this awesome project

**Comment by marquisvictor** [comment]
Yeah, well, its still in progress though, but you could as well just fork and clone it to your local machine. 
Open the index mark-up file, and voila!! Its in your browser. 

If you plan to develop or build on it;

open a terminal in the folder where the repo is cloned, then you type `npm install` I suppose you have node installed already. This is to install the external dependencies for the project, e.g scss. 

Then to make changes/build on it, fire up the terminal again and type `npm run compile:sass`

After that, you can start tearing it apart 😄
